version: '3.8'

volumes:
  zookeeper_data:
    name: zookeeper_data
  kafka_data:
    name: kafka_data

services:
  vote-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - kafka
      - mysql
    command: 'mvn spring-boot:run'
    environment:
      - PROFILE=dev
      - JAVA_TOOL_OPTIONS="-Xmx512m"
      - DATABASE_HOST=mysql
      - DATABASE_USER=admin-vote-api
      - DATABASE_PASSWORD=123456
      - DATABASE_NAME=vote-database
      - DATABASE_PORT=3306
    volumes:
      - './configuration:/tmp/configuration:delegated'
      - './vote-api:/tmp/app:delegated'
      - '~/.m2:/home/deploy/.m2:cached'
    networks:
      - default

  zookeeper:
    image: 'bitnami/zookeeper:3'
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:2'
    ports:
      - '9092:9092'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - 'KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181'
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper

  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=vote-database
      - MYSQL_USER=admin-vote-api
      - MYSQL_PASSWORD=123456